print("Por favor ingrese los siguientes datos")
print("Nombres:")
nombre = input()
print("Apellidos:")
apellidos = input()
print("Edad:")
edad = input()
print("Fecha de nacimiento:")
fecha = input()
print("Genero:")
genero = input()

print("Nombres: ",nombre)
print("Apellidos: ",apellidos)
print("Fecha de Nacimiento: ",fecha)
print("Genero: ",genero)

